export const SET_DATA = 'SET_DATA';
export const SET_ALLOW_USER_INTERACTION = 'SET_ALLOW_USER_INTERACTION';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_LOADING_AND_DATA = 'SET_LOADING_AND_DATA';
